import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // productSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  productSidebar: [
    'products/README',
    {
      type: 'category',
      label: 'India Market Connector',
      link: {
        type: 'doc',
        id: 'products/imc/README',
      },
      items: [
        'products/imc/SUMMARY',
        'products/imc/broker-setup-and-local-deployment',
        'products/imc/python-sdk',
        {
          type: 'category',
          label: 'IMC API v1',
          link: {
            type: 'doc',
            id: 'products/imc/api-documentation/v1/README',
          },
          items: [{type: 'autogenerated', dirName: 'products/imc/api-documentation/v1'}],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: [
            {type: 'autogenerated', dirName: 'products/imc/trading-platform'},
            {type: 'autogenerated', dirName: 'products/imc/connect-brokers'},
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            'products/imc/symbol-format',
            'products/imc/strategy-management',
            'products/imc/mcp',
            'products/imc/static-ip',
            'products/imc/latency',
            'products/imc/community-support',
            'products/imc/mini-foss-universe',
            'products/imc/why-to-build-with-Layr0',
          ],
        },
        {type: 'autogenerated', dirName: 'products/imc/new-features'},
      ],
    },
  ],
};

export default sidebars;
